// Contenus du site — Raouf Tchakondo
// Tout ce qui est marqué `null` ou `demo: true` est à compléter / vérifier avec Raouf
// (cf. cahier des charges, section 2 « À vérifier » et section 9 « À collecter »).

export const config = {
  // Domaine cible (cahier des charges, section 6). Sert aux URL canoniques et au sitemap.
  siteUrl: 'https://raouftchakondo.com',
  email: 'booking@raouftchakondo.com',
  pressEmail: 'presse@raouftchakondo.com',
  // Numéro WhatsApp au format international sans « + » ni espaces (ex. 22890000000). Vide = masqué.
  whatsapp: '',
  social: [
    { name: 'Facebook', url: 'https://www.facebook.com/' },
    { name: 'Instagram', url: 'https://www.instagram.com/' },
    { name: 'YouTube', url: 'https://www.youtube.com/' },
  ],
  // Tant que `true`, un bandeau signale que le site est une préproduction avec données d'exemple.
  preview: true,
};

// Rubriques : identifiant → segment d'URL par langue
export const routes = {
  home: { fr: '', en: '' },
  bio: { fr: 'biographie', en: 'biography' },
  creations: { fr: 'creations', en: 'works' },
  langage: { fr: 'langage', en: 'language' },
  aske: { fr: 'aske-danse', en: 'aske-danse' },
  transmission: { fr: 'transmission', en: 'teaching' },
  collaborations: { fr: 'collaborations', en: 'collaborations' },
  presse: { fr: 'presse', en: 'press' },
  contact: { fr: 'contact', en: 'contact' },
};

export const nav = ['bio', 'creations', 'langage', 'aske', 'transmission', 'collaborations', 'presse'];

export const ui = {
  fr: {
    lang: 'Français',
    otherLang: 'English',
    skip: 'Aller au contenu',
    menu: 'Menu',
    close: 'Fermer',
    theme: 'Changer de thème',
    home: 'Accueil',
    pages: {
      home: 'Accueil',
      bio: 'Biographie',
      creations: 'Créations',
      langage: 'Le langage',
      aske: 'Aské Danse',
      transmission: 'Transmission',
      collaborations: 'Collaborations',
      presse: 'Presse',
      contact: 'Contact & booking',
    },
    role: 'Danseur · Chorégraphe · Pédagogue',
    signature: ['Le corps comme géométrie.', 'Les racines comme langage.'],
    preview: 'Préproduction — textes, dates et médias en cours de validation. Les éléments marqués « Exemple » sont fictifs.',
    todo: 'À confirmer',
    example: 'Exemple',
    mediaSoon: 'Image à venir — tournage dédié',
    videoSoon: 'Vidéo à venir — tournage dédié',
    nextDates: 'Prochaines dates',
    allDates: 'Tout l’agenda',
    noDates: 'Les prochaines dates seront annoncées ici.',
    addCal: 'Ajouter au calendrier',
    places: (n) => (n === 0 ? 'Complet' : n === 1 ? '1 place restante' : `${n} places restantes`),
    newsletter: 'Newsletter',
    newsletterText: 'Créations, tournées, stages. Une lettre par saison.',
    email: 'Adresse e-mail',
    audience: 'Je suis',
    audiencePro: 'Professionnel·le (programmation, presse, institution)',
    audienceStudent: 'Danseur·se, élève',
    subscribe: 'S’inscrire',
    subscribed: 'Merci. Confirmez votre inscription depuis l’e-mail que vous allez recevoir.',
    booking: 'Booking',
    follow: 'Suivre',
    whatsapp: 'Écrire sur WhatsApp',
    rights: 'Tous droits réservés.',
    seeAll: 'Voir toutes les créations',
    program: 'Programmer cette pièce',
    back: 'Retour aux créations',
    filterAll: 'Tout',
    filterFormat: 'Format',
    filterYear: 'Année',
    formats: { solo: 'Solo', duo: 'Duo', groupe: 'Groupe', theatre: 'Théâtre' },
    synopsis: 'Synopsis',
    cast: 'Distribution',
    duration: 'Durée',
    year: 'Création',
    format: 'Format',
    teaser: 'Teaser 30 s',
    gallery: 'Galerie',
    techSheet: 'Fiche technique (PDF)',
    techSheetSoon: 'Fiche technique en préparation',
    tourDates: 'Dates de tournée',
    copy: 'Copier',
    copied: 'Copié',
    send: 'Envoyer',
    required: 'obligatoire',
    formSent: 'Votre messagerie va s’ouvrir avec la demande pré-remplie. Si rien ne se passe, écrivez à',
    country: 'Pays',
    allCountries: 'Tous les pays',
  },
  en: {
    lang: 'English',
    otherLang: 'Français',
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    theme: 'Toggle theme',
    home: 'Home',
    pages: {
      home: 'Home',
      bio: 'Biography',
      creations: 'Works',
      langage: 'The language',
      aske: 'Aské Danse',
      transmission: 'Teaching',
      collaborations: 'Collaborations',
      presse: 'Press',
      contact: 'Contact & booking',
    },
    role: 'Dancer · Choreographer · Teacher',
    signature: ['The body as geometry.', 'Roots as language.'],
    preview: 'Pre-production — texts, dates and media are being validated. Items marked “Example” are fictitious.',
    todo: 'To be confirmed',
    example: 'Example',
    mediaSoon: 'Image coming — dedicated shoot',
    videoSoon: 'Video coming — dedicated shoot',
    nextDates: 'Upcoming dates',
    allDates: 'Full calendar',
    noDates: 'Upcoming dates will be announced here.',
    addCal: 'Add to calendar',
    places: (n) => (n === 0 ? 'Sold out' : n === 1 ? '1 place left' : `${n} places left`),
    newsletter: 'Newsletter',
    newsletterText: 'Works, tours, workshops. One letter per season.',
    email: 'Email address',
    audience: 'I am',
    audiencePro: 'A professional (programming, press, institution)',
    audienceStudent: 'A dancer or student',
    subscribe: 'Subscribe',
    subscribed: 'Thank you. Please confirm your subscription from the email you are about to receive.',
    booking: 'Booking',
    follow: 'Follow',
    whatsapp: 'Message on WhatsApp',
    rights: 'All rights reserved.',
    seeAll: 'See all works',
    program: 'Book this piece',
    back: 'Back to works',
    filterAll: 'All',
    filterFormat: 'Format',
    filterYear: 'Year',
    formats: { solo: 'Solo', duo: 'Duet', groupe: 'Ensemble', theatre: 'Theatre' },
    synopsis: 'Synopsis',
    cast: 'Cast',
    duration: 'Duration',
    year: 'Premiere',
    format: 'Format',
    teaser: '30 s teaser',
    gallery: 'Gallery',
    techSheet: 'Technical rider (PDF)',
    techSheetSoon: 'Technical rider in preparation',
    tourDates: 'Tour dates',
    copy: 'Copy',
    copied: 'Copied',
    send: 'Send',
    required: 'required',
    formSent: 'Your email app will open with the request pre-filled. If nothing happens, write to',
    country: 'Country',
    allCountries: 'All countries',
  },
};

// Preuves factuelles (cahier des charges, section 2)
export const proofs = {
  fr: [
    { k: '2011', v: 'Assistant de Germaine Acogny, diplômé de l’École des Sables' },
    { k: '2005', v: 'Fonde à Lomé la compagnie Aské Danse' },
    { k: '3 pays', v: 'Formé en Belgique, en France (CND, Pantin) et au Sénégal' },
    { k: 'Théâtre', v: 'Chorégraphie d’Isis-Antigone, texte de Kossi Efoui' },
  ],
  en: [
    { k: '2011', v: 'Assistant to Germaine Acogny, graduate of École des Sables' },
    { k: '2005', v: 'Founded the Aské Danse company in Lomé' },
    { k: '3 countries', v: 'Trained in Belgium, France (CND, Pantin) and Senegal' },
    { k: 'Theatre', v: 'Choreography for Isis-Antigone, text by Kossi Efoui' },
  ],
};

export const bio = {
  fr: {
    short:
      'Raouf Tchakondo est danseur, chorégraphe et pédagogue, né à Lomé. Formé au sein de la Sojaf, puis auprès de Motra et d’Harold George, il poursuit sa formation en Belgique avec Nyanga Zam, au Centre national de la danse à Pantin et à l’École des Sables au Sénégal. Il fonde la compagnie Aské Danse en 2005. Depuis 2011, il est l’assistant de Germaine Acogny. Son écriture relie la géométrie du corps aux danses vodou du Sud et aux danses traditionnelles du Nord Togo.',
    long: [
      'Raouf Tchakondo naît à Lomé. Il commence la danse à la fin des années 1990 au sein de la Sojaf. Sa formation passe ensuite par Motra et par Harold George, avant de le conduire vers Germaine Acogny.',
      'En 2003, il se forme en Belgique avec Nyanga Zam. En 2009, il suit une formation au Centre national de la danse, à Pantin. Au Sénégal, il est diplômé de l’École des Sables, le centre fondé par Germaine Acogny à Toubab Dialaw. Il en devient l’assistant en 2011.',
      'En 2005, il fonde à Lomé la compagnie Aské Danse. La compagnie crée, tourne et forme. Elle accompagne une nouvelle génération de danseurs, de la Maison des Artistes Danseurs au collectif Street Kings.',
      'Son écriture part de figures géométriques : le cercle, le triangle, le losange. Il les nourrit des danses vodou du Sud du Togo et des danses traditionnelles du Nord — Adjogbo, Hébiésso, Gadao, Kondona — et de la technique Acogny.',
      'Ses pièces — Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui — ont circulé en Afrique de l’Ouest et en Europe. Dansons tous ! réunit des danseurs valides et des danseurs à mobilité réduite. Pour le théâtre, il signe la chorégraphie d’Isis-Antigone, sur un texte de Kossi Efoui.',
    ],
  },
  en: {
    short:
      'Raouf Tchakondo is a dancer, choreographer and teacher born in Lomé, Togo. He trained with Sojaf, then with Motra and Harold George, before continuing in Belgium with Nyanga Zam, at the Centre national de la danse in Pantin, France, and at École des Sables in Senegal. He founded the Aské Danse company in 2005. Since 2011 he has been assistant to Germaine Acogny. His work connects the geometry of the body with the vodou dances of southern Togo and the traditional dances of the north.',
    long: [
      'Raouf Tchakondo was born in Lomé. He began dancing in the late 1990s with Sojaf. His training then led him to Motra and Harold George, and on to Germaine Acogny.',
      'In 2003 he trained in Belgium with Nyanga Zam. In 2009 he studied at the Centre national de la danse in Pantin, France. In Senegal he graduated from École des Sables, the centre founded by Germaine Acogny in Toubab Dialaw. He became her assistant in 2011.',
      'In 2005 he founded the Aské Danse company in Lomé. The company creates, tours and trains. It supports a new generation of dancers, from the Maison des Artistes Danseurs to the Street Kings collective.',
      'His choreographic writing starts from geometric figures: the circle, the triangle, the diamond. He feeds them with the vodou dances of southern Togo and the traditional dances of the north — Adjogbo, Hébiésso, Gadao, Kondona — and with the Acogny technique.',
      'His pieces — Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui — have travelled across West Africa and Europe. Dansons tous ! brings together able-bodied dancers and dancers with reduced mobility. For the theatre, he choreographed Isis-Antigone, from a text by Kossi Efoui.',
    ],
  },
};

// Frise 1998 → 2026
export const timeline = [
  { year: '1998', place: 'Lomé', fr: 'Premiers pas de danseur au sein de la Sojaf.', en: 'First steps as a dancer with Sojaf.' },
  { year: '2003', place: 'Belgique', placeEn: 'Belgium', fr: 'Formation avec Nyanga Zam.', en: 'Training with Nyanga Zam.' },
  { year: '2005', place: 'Lomé', fr: 'Fonde la compagnie Aské Danse.', en: 'Founds the Aské Danse company.' },
  { year: '2009', place: 'Pantin', fr: 'Formation au Centre national de la danse.', en: 'Training at the Centre national de la danse.' },
  { year: '2011', place: 'Toubab Dialaw', fr: 'École des Sables. Devient l’assistant de Germaine Acogny.', en: 'École des Sables. Becomes assistant to Germaine Acogny.' },
  { year: '2026', place: 'Lomé', fr: 'Aské Danse crée, tourne et forme la relève.', en: 'Aské Danse creates, tours and trains the next generation.' },
];

export const lineage = ['Sojaf', 'Motra', 'Harold George', 'Germaine Acogny'];

// Carte : lieux de formation et de tournée. `year: null` = date à confirmer.
export const places = [
  { name: 'Lomé', lon: 1.23, lat: 6.13, year: 1998, kind: 'base', label: 'below' },
  { name: 'Bruxelles', nameEn: 'Brussels', lon: 4.35, lat: 50.85, year: 2003, kind: 'formation' },
  { name: 'Pantin', lon: 2.41, lat: 48.89, year: 2009, kind: 'formation' },
  { name: 'Toubab Dialaw', lon: -17.14, lat: 14.6, year: 2011, kind: 'formation' },
  { name: 'Cotonou', lon: 2.42, lat: 6.37, year: null, kind: 'tournee', label: 'above' },
  { name: 'Abidjan', lon: -4.01, lat: 5.36, year: null, kind: 'tournee', label: 'left' },
];

// Répertoire. Les champs null sont à compléter avec la compagnie.
// `shape` : forme géométrique propre à chaque pièce (direction artistique).
export const creations = [
  {
    slug: 'kebia-et-kola',
    title: 'Kébia et Kola',
    shape: 'circle',
    format: null,
    year: null,
    duration: null,
    cast: null,
    featured: true,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'nale-et-essime',
    title: 'Nalè et Essime',
    shape: 'losange',
    format: null,
    year: null,
    duration: null,
    cast: null,
    featured: true,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'dansons-tous',
    title: 'Dansons tous !',
    shape: 'hexagon',
    format: 'groupe',
    year: null,
    duration: null,
    cast: null,
    featured: true,
    synopsis: {
      fr: 'Une pièce pour danseurs valides et danseurs à mobilité réduite. Un même plateau, une même écriture.',
      en: 'A piece for able-bodied dancers and dancers with reduced mobility. One stage, one choreographic language.',
    },
  },
  {
    slug: 'l-oeil',
    title: 'L’Œil',
    shape: 'eye',
    format: null,
    year: null,
    duration: null,
    cast: null,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'elle-et-lui',
    title: 'Elle et Lui',
    shape: 'triangle',
    format: null,
    year: null,
    duration: null,
    cast: null,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'isis-antigone',
    title: 'Isis-Antigone',
    shape: 'square',
    format: 'theatre',
    year: null,
    duration: null,
    cast: null,
    synopsis: {
      fr: 'Chorégraphie pour la pièce de théâtre de Kossi Efoui.',
      en: 'Choreography for Kossi Efoui’s play.',
    },
  },
];

// Le langage : danses sources et figures associées (association à valider avec Raouf)
export const sources = [
  {
    id: 'adjogbo',
    name: 'Adjogbo',
    shape: 'circle',
    fr: { origin: 'Sud — vodou', text: 'Dans l’écriture : le cercle. La communauté, la pulsation, le retour.' },
    en: { origin: 'South — vodou', text: 'In the writing: the circle. Community, pulse, return.' },
  },
  {
    id: 'hebiesso',
    name: 'Hébiésso',
    shape: 'triangle',
    fr: { origin: 'Sud — vodou', text: 'Dans l’écriture : le triangle. L’élan, la verticale, la frappe.' },
    en: { origin: 'South — vodou', text: 'In the writing: the triangle. Surge, verticality, strike.' },
  },
  {
    id: 'gadao',
    name: 'Gadao',
    shape: 'losange',
    fr: { origin: 'Nord Togo', text: 'Dans l’écriture : le losange. L’équilibre entre deux appuis.' },
    en: { origin: 'Northern Togo', text: 'In the writing: the diamond. Balance between two points of support.' },
  },
  {
    id: 'kondona',
    name: 'Kondona',
    shape: 'square',
    fr: { origin: 'Nord Togo', text: 'Dans l’écriture : le carré. Le sol, l’ancrage, la stabilité.' },
    en: { origin: 'Northern Togo', text: 'In the writing: the square. Ground, anchoring, stability.' },
  },
  {
    id: 'acogny',
    name: 'Technique Acogny',
    nameEn: 'Acogny technique',
    shape: 'spiral',
    fr: { origin: 'École des Sables', text: 'La colonne vertébrale, les ondulations, la relation au sol. Une technique qu’il transmet aux côtés de Germaine Acogny depuis 2011.' },
    en: { origin: 'École des Sables', text: 'The spine, undulations, the relationship to the ground. A technique he has taught alongside Germaine Acogny since 2011.' },
  },
];

// Agenda. `demo: true` = donnée d'exemple, non publiée en données structurées.
export const agenda = [
  {
    id: 'ex-stage-lome',
    demo: true,
    date: '2026-11-14',
    end: '2026-11-18',
    type: 'stage',
    city: 'Lomé',
    country: 'Togo',
    fr: 'Stage — technique Acogny et écriture géométrique',
    en: 'Workshop — Acogny technique and geometric writing',
    venue: 'Studio Aské Danse',
    price: 45000,
    currency: 'XOF',
    seats: 20,
    left: 7,
  },
  {
    id: 'ex-masterclass-cotonou',
    demo: true,
    date: '2026-12-05',
    end: '2026-12-06',
    type: 'stage',
    city: 'Cotonou',
    country: 'Bénin',
    countryEn: 'Benin',
    fr: 'Masterclass — danses sources du Togo',
    en: 'Masterclass — source dances of Togo',
    venue: null,
    price: 30000,
    currency: 'XOF',
    seats: 16,
    left: 12,
  },
  {
    id: 'ex-spectacle-abidjan',
    demo: true,
    date: '2027-01-23',
    type: 'spectacle',
    city: 'Abidjan',
    country: 'Côte d’Ivoire',
    countryEn: 'Côte d’Ivoire',
    fr: 'Dansons tous ! — représentation',
    en: 'Dansons tous ! — performance',
    piece: 'dansons-tous',
    venue: null,
  },
];

export const pages = {
  fr: {
    home: {
      title: 'Raouf Tchakondo — danseur et chorégraphe, Lomé',
      description:
        'Raouf Tchakondo, danseur, chorégraphe et pédagogue togolais. Assistant de Germaine Acogny, fondateur d’Aské Danse. Créations, stages, booking.',
      manifesto: 'Vidéo manifeste — 60 s',
      ctaWorks: 'Voir les créations',
      ctaBook: 'Programmer une pièce',
      featured: 'Créations',
      proofTitle: 'Repères',
      mapTitle: 'Formations et tournées',
      mapText: 'De Lomé à Bruxelles, de Pantin à Toubab Dialaw. Les villes s’allument année après année.',
      mapLink: 'Voir le parcours complet',
      pathsTitle: 'Vous êtes',
      paths: [
        { who: 'Programmateur·rice', what: 'Répertoire, fiches techniques, devis de tournée', to: 'creations' },
        { who: 'Institution, bailleur', what: 'Parcours, engagement social, résidences', to: 'bio' },
        { who: 'Danseur·se, élève', what: 'Stages, masterclasses, inscription en ligne', to: 'transmission' },
        { who: 'Marque, agence', what: 'Chorégraphie de lancement, clip, cérémonie', to: 'collaborations' },
        { who: 'Journaliste, chercheur·se', what: 'Bios, photos HD, articles', to: 'presse' },
      ],
      placesTitle: 'Lieux de formation',
      placesNote: 'Logos partenaires : autorisations en cours.',
    },
    bio: {
      title: 'Biographie',
      description: 'Biographie de Raouf Tchakondo : de la Sojaf à Germaine Acogny, la fondation d’Aské Danse, 1998 → 2026.',
      lead: 'Né à Lomé. Formé à Lomé, Bruxelles, Pantin et Toubab Dialaw. Assistant de Germaine Acogny depuis 2011.',
      shortTitle: 'En 80 mots',
      longTitle: 'Parcours',
      timelineTitle: '1998 → 2026',
      lineageTitle: 'Filiation',
      lineageText: 'Une transmission de maître à élève, jusqu’à la référence de la danse africaine contemporaine.',
    },
    creations: {
      title: 'Créations',
      description: 'Le répertoire de Raouf Tchakondo et d’Aské Danse : Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui, Isis-Antigone.',
      lead: 'Quinze ans d’écriture. Chaque pièce a sa forme.',
    },
    langage: {
      title: 'Le langage',
      description: 'L’écriture chorégraphique de Raouf Tchakondo : géométrie du corps, danses vodou du Sud et danses du Nord Togo, technique Acogny.',
      lead: 'Une écriture fondée sur les figures géométriques, nourrie des danses vodou du Sud et des danses traditionnelles du Nord Togo.',
      intro: [
        'Le corps trace des figures. Un cercle au sol, un triangle dans l’espace, un losange entre deux appuis.',
        'Ces figures ne sont pas des décors. Elles organisent le mouvement, les trajectoires, les relations entre danseurs.',
        'Chaque figure a une source : une danse apprise, transmise, retravaillée.',
      ],
      moduleTitle: 'Les sources',
      moduleHint: 'Choisissez une danse pour voir sa figure.',
      interview: 'Entretien — le langage chorégraphique (sous-titré FR / EN)',
    },
    aske: {
      title: 'Aské Danse',
      description: 'Aské Danse, compagnie de danse contemporaine fondée à Lomé en 2005 par Raouf Tchakondo. Répertoire, danseurs, recrutement.',
      lead: 'Compagnie fondée à Lomé en 2005. Elle crée, tourne et forme.',
      history: [
        'Aské Danse naît à Lomé en 2005. Raouf Tchakondo la fonde pour porter ses créations et pour former des danseurs.',
        'La compagnie accompagne une nouvelle génération : les danseurs de la Maison des Artistes Danseurs, le collectif Street Kings.',
        'Ses interprètes sont un vivier professionnel pour les festivals, les théâtres et les productions de la région.',
      ],
      dancersTitle: 'Les danseurs',
      dancersNote: 'Portraits vidéo en boucle — tournage à venir.',
      relTitle: 'La relève',
      rel: [
        { name: 'Maison des Artistes Danseurs', text: 'Formation de jeunes interprètes.' },
        { name: 'Street Kings', text: 'Des danses urbaines à la scène contemporaine.' },
      ],
      repTitle: 'Répertoire',
      recruitTitle: 'Recrutement',
      recruitText: 'Vous êtes danseur ou danseuse et souhaitez rejoindre la compagnie ? Envoyez une présentation et un lien vidéo.',
      recruitCta: 'Candidater',
    },
    transmission: {
      title: 'Transmission',
      description: 'Stages et masterclasses de danse contemporaine avec Raouf Tchakondo : technique Acogny, danses sources du Togo. Inscription et paiement en ligne.',
      lead: 'Stages, masterclasses, cours. La technique Acogny et les danses sources du Togo.',
      offers: [
        { t: 'Stages', d: 'Plusieurs jours de travail intensif. Technique, répertoire, écriture.' },
        { t: 'Masterclasses', d: 'Une ou deux journées, en festival ou en institution.' },
        { t: 'Cours en ligne', d: 'Technique Acogny, bases. Bientôt disponibles.' },
      ],
      agendaTitle: 'Agenda des stages',
      formTitle: 'Inscription',
      session: 'Session',
      qty: 'Nombre de places',
      name: 'Nom complet',
      phone: 'Téléphone',
      level: 'Niveau',
      levels: ['Débutant', 'Intermédiaire', 'Professionnel'],
      pay: 'Paiement',
      payMomo: 'Mobile money',
      payCard: 'Carte bancaire',
      total: 'Total',
      submit: 'Réserver et payer',
      demoPay: 'Paiement en préproduction : la réservation est transmise par e-mail, le paiement FedaPay / Stripe sera activé au lancement.',
      schoolTitle: 'Écoles et institutions',
      schoolText: 'Ateliers sur mesure pour écoles, conservatoires et centres culturels.',
    },
    collaborations: {
      title: 'Collaborations',
      description: 'Chorégraphie pour le théâtre, les clips, les marques et les événements. Envoyez votre brief à Raouf Tchakondo.',
      lead: 'Théâtre, clips, marques, événements. Une écriture reconnaissable, au service d’un projet.',
      fields: [
        { t: 'Théâtre', d: 'Chorégraphie d’Isis-Antigone, texte de Kossi Efoui.' },
        { t: 'Clips', d: 'Chorégraphie et direction de danseurs pour la musique.' },
        { t: 'Marques', d: 'Lancements, films, activations.' },
        { t: 'Événements', d: 'Cérémonies, ouvertures, créations in situ.' },
      ],
      casesTitle: 'Études de cas',
      casesNote: 'Avant / après — à documenter avec les premiers projets.',
      briefTitle: 'Votre brief',
    },
    presse: {
      title: 'Presse',
      description: 'Espace presse de Raouf Tchakondo : biographies courte et longue, photos HD, kit presse, contact.',
      lead: 'Biographies, photos, kit presse. Tout en un clic.',
      kitTitle: 'Kit presse',
      kitItems: ['Biographies courte et longue', 'Photos HD (fond noir, fond blanc)', 'Logos', 'Fiches des créations'],
      kitCta: 'Télécharger le kit presse',
      kitSoon: 'Le kit complet (PDF + ZIP) sera généré depuis le CMS. En attendant, demandez-le par e-mail.',
      bioShort: 'Bio courte',
      bioLong: 'Bio longue',
      articlesTitle: 'Ils en parlent',
      articles: [
        { src: 'Togocultures', t: 'Portrait de Raouf Tchakondo', y: '2016' },
        { src: 'Africultures', t: 'Fiche Raouf Tchakondo', y: null },
        { src: 'Numeridanse', t: 'Profil', y: null },
        { src: 'Sceneweb', t: 'Isis-Antigone de Kossi Efoui', y: null },
      ],
      contactTitle: 'Contact presse',
    },
    contact: {
      title: 'Contact & booking',
      description: 'Booking Raouf Tchakondo et Aské Danse : tournée, atelier, collaboration, presse.',
      lead: 'Tournée, atelier, collaboration, presse. Chaque demande reçoit une réponse.',
      type: 'Type de demande',
      types: { tournee: 'Tournée / programmation', atelier: 'Atelier / masterclass', collaboration: 'Collaboration', presse: 'Presse', autre: 'Autre' },
      piece: 'Pièce concernée',
      pieceNone: 'Aucune en particulier',
      org: 'Structure',
      name: 'Nom',
      email: 'E-mail',
      phone: 'Téléphone / WhatsApp',
      dates: 'Dates envisagées',
      place: 'Ville, pays',
      budget: 'Budget indicatif',
      budgets: ['Non défini', '< 1 000 €', '1 000 – 5 000 €', '5 000 – 15 000 €', '> 15 000 €'],
      message: 'Message',
    },
  },
  en: {
    home: {
      title: 'Raouf Tchakondo — dancer and choreographer, Lomé',
      description:
        'Raouf Tchakondo, Togolese dancer, choreographer and teacher. Assistant to Germaine Acogny, founder of Aské Danse. Works, workshops, booking.',
      manifesto: 'Manifesto video — 60 s',
      ctaWorks: 'See the works',
      ctaBook: 'Book a piece',
      featured: 'Works',
      proofTitle: 'Landmarks',
      mapTitle: 'Training and touring',
      mapText: 'From Lomé to Brussels, from Pantin to Toubab Dialaw. The cities light up year after year.',
      mapLink: 'See the full journey',
      pathsTitle: 'You are',
      paths: [
        { who: 'A programmer', what: 'Repertoire, technical riders, touring quote', to: 'creations' },
        { who: 'An institution or funder', what: 'Career, social impact, residencies', to: 'bio' },
        { who: 'A dancer or student', what: 'Workshops, masterclasses, online booking', to: 'transmission' },
        { who: 'A brand or agency', what: 'Launch choreography, music video, ceremony', to: 'collaborations' },
        { who: 'A journalist or researcher', what: 'Bios, HD photos, articles', to: 'presse' },
      ],
      placesTitle: 'Where he trained',
      placesNote: 'Partner logos: permissions in progress.',
    },
    bio: {
      title: 'Biography',
      description: 'Biography of Raouf Tchakondo: from Sojaf to Germaine Acogny, founding Aské Danse, 1998 → 2026.',
      lead: 'Born in Lomé. Trained in Lomé, Brussels, Pantin and Toubab Dialaw. Assistant to Germaine Acogny since 2011.',
      shortTitle: 'In 80 words',
      longTitle: 'Journey',
      timelineTitle: '1998 → 2026',
      lineageTitle: 'Lineage',
      lineageText: 'A transmission from teacher to student, up to the reference of contemporary African dance.',
    },
    creations: {
      title: 'Works',
      description: 'The repertoire of Raouf Tchakondo and Aské Danse: Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui, Isis-Antigone.',
      lead: 'Fifteen years of writing. Each piece has its own shape.',
    },
    langage: {
      title: 'The language',
      description: 'Raouf Tchakondo’s choreographic language: geometry of the body, southern vodou dances and northern Togolese dances, Acogny technique.',
      lead: 'A choreographic writing built on geometric figures, fed by the vodou dances of the South and the traditional dances of northern Togo.',
      intro: [
        'The body draws figures. A circle on the floor, a triangle in space, a diamond between two points of support.',
        'These figures are not decoration. They organise movement, trajectories, the relationships between dancers.',
        'Each figure has a source: a dance learned, passed on, reworked.',
      ],
      moduleTitle: 'The sources',
      moduleHint: 'Choose a dance to see its figure.',
      interview: 'Interview — the choreographic language (FR / EN subtitles)',
    },
    aske: {
      title: 'Aské Danse',
      description: 'Aské Danse, contemporary dance company founded in Lomé in 2005 by Raouf Tchakondo. Repertoire, dancers, auditions.',
      lead: 'A company founded in Lomé in 2005. It creates, tours and trains.',
      history: [
        'Aské Danse was born in Lomé in 2005. Raouf Tchakondo founded it to carry his works and to train dancers.',
        'The company supports a new generation: the dancers of the Maison des Artistes Danseurs, the Street Kings collective.',
        'Its performers are a professional talent pool for festivals, theatres and productions across the region.',
      ],
      dancersTitle: 'The dancers',
      dancersNote: 'Looping video portraits — shoot coming.',
      relTitle: 'The next generation',
      rel: [
        { name: 'Maison des Artistes Danseurs', text: 'Training young performers.' },
        { name: 'Street Kings', text: 'From urban dance to the contemporary stage.' },
      ],
      repTitle: 'Repertoire',
      recruitTitle: 'Auditions',
      recruitText: 'Are you a dancer who would like to join the company? Send a short introduction and a video link.',
      recruitCta: 'Apply',
    },
    transmission: {
      title: 'Teaching',
      description: 'Contemporary dance workshops and masterclasses with Raouf Tchakondo: Acogny technique, source dances of Togo. Online booking and payment.',
      lead: 'Workshops, masterclasses, classes. The Acogny technique and the source dances of Togo.',
      offers: [
        { t: 'Workshops', d: 'Several days of intensive work. Technique, repertoire, writing.' },
        { t: 'Masterclasses', d: 'One or two days, at festivals or institutions.' },
        { t: 'Online classes', d: 'Acogny technique, foundations. Coming soon.' },
      ],
      agendaTitle: 'Workshop calendar',
      formTitle: 'Registration',
      session: 'Session',
      qty: 'Number of places',
      name: 'Full name',
      phone: 'Phone',
      level: 'Level',
      levels: ['Beginner', 'Intermediate', 'Professional'],
      pay: 'Payment',
      payMomo: 'Mobile money',
      payCard: 'Card',
      total: 'Total',
      submit: 'Book and pay',
      demoPay: 'Pre-production payment: your booking is sent by email; FedaPay / Stripe payment will be enabled at launch.',
      schoolTitle: 'Schools and institutions',
      schoolText: 'Tailored workshops for schools, conservatoires and cultural centres.',
    },
    collaborations: {
      title: 'Collaborations',
      description: 'Choreography for theatre, music videos, brands and events. Send your brief to Raouf Tchakondo.',
      lead: 'Theatre, music videos, brands, events. A recognisable language, at the service of a project.',
      fields: [
        { t: 'Theatre', d: 'Choreography for Isis-Antigone, text by Kossi Efoui.' },
        { t: 'Music videos', d: 'Choreography and dancer direction for music.' },
        { t: 'Brands', d: 'Launches, films, activations.' },
        { t: 'Events', d: 'Ceremonies, openings, site-specific pieces.' },
      ],
      casesTitle: 'Case studies',
      casesNote: 'Before / after — to be documented with the first projects.',
      briefTitle: 'Your brief',
    },
    presse: {
      title: 'Press',
      description: 'Raouf Tchakondo press area: short and long bios, HD photos, press kit, contact.',
      lead: 'Bios, photos, press kit. All in one click.',
      kitTitle: 'Press kit',
      kitItems: ['Short and long bios', 'HD photos (black and white backgrounds)', 'Logos', 'Work sheets'],
      kitCta: 'Download the press kit',
      kitSoon: 'The full kit (PDF + ZIP) will be generated from the CMS. Meanwhile, request it by email.',
      bioShort: 'Short bio',
      bioLong: 'Long bio',
      articlesTitle: 'Coverage',
      articles: [
        { src: 'Togocultures', t: 'Portrait of Raouf Tchakondo', y: '2016' },
        { src: 'Africultures', t: 'Raouf Tchakondo profile', y: null },
        { src: 'Numeridanse', t: 'Profile', y: null },
        { src: 'Sceneweb', t: 'Isis-Antigone by Kossi Efoui', y: null },
      ],
      contactTitle: 'Press contact',
    },
    contact: {
      title: 'Contact & booking',
      description: 'Booking Raouf Tchakondo and Aské Danse: touring, workshops, collaborations, press.',
      lead: 'Touring, workshops, collaborations, press. Every request gets an answer.',
      type: 'Request type',
      types: { tournee: 'Touring / programming', atelier: 'Workshop / masterclass', collaboration: 'Collaboration', presse: 'Press', autre: 'Other' },
      piece: 'Piece',
      pieceNone: 'None in particular',
      org: 'Organisation',
      name: 'Name',
      email: 'Email',
      phone: 'Phone / WhatsApp',
      dates: 'Proposed dates',
      place: 'City, country',
      budget: 'Indicative budget',
      budgets: ['Not defined', '< €1,000', '€1,000 – 5,000', '€5,000 – 15,000', '> €15,000'],
      message: 'Message',
    },
  },
};
