// Contenus du site — Raouf Tchakondo
// Tout ce qui est marqué `null` ou `demo: true` est à compléter / vérifier avec Raouf
// (cf. cahier des charges, section 2 « À vérifier » et section 9 « À collecter »).

export const config = {
  // Domaine cible (cahier des charges, section 6). Sert aux URL canoniques et au sitemap.
  siteUrl: 'https://raouftchakondo.com',
  email: 'booking@raouftchakondo.com',
  pressEmail: 'presse@raouftchakondo.com',
  // Numéro WhatsApp au format international sans « + » ni espaces (ex. 22890000000). Vide = masqué.
  whatsapp: '',
  social: [
    { name: 'Facebook', url: 'https://www.facebook.com/' },
    { name: 'Instagram', url: 'https://www.instagram.com/' },
    { name: 'YouTube', url: 'https://www.youtube.com/' },
  ],
  // Tant que `true`, un bandeau signale que le site est une préproduction avec données d'exemple.
  preview: true,
};

// Rubriques : identifiant → segment d'URL par langue
export const routes = {
  home: { fr: '', en: '' },
  bio: { fr: 'biographie', en: 'biography' },
  creations: { fr: 'creations', en: 'works' },
  langage: { fr: 'langage', en: 'language' },
  aske: { fr: 'aske-danse', en: 'aske-danse' },
  transmission: { fr: 'transmission', en: 'teaching' },
  collaborations: { fr: 'collaborations', en: 'collaborations' },
  presse: { fr: 'presse', en: 'press' },
  contact: { fr: 'contact', en: 'contact' },
};

export const nav = ['bio', 'creations', 'langage', 'aske', 'transmission', 'collaborations', 'presse'];

export const ui = {
  fr: {
    lang: 'Français',
    otherLang: 'English',
    skip: 'Aller au contenu',
    menu: 'Menu',
    close: 'Fermer',
    theme: 'Changer de thème',
    home: 'Accueil',
    pages: {
      home: 'Accueil',
      bio: 'Biographie',
      creations: 'Créations',
      langage: 'Le langage',
      aske: 'Aské Danse',
      transmission: 'Transmission',
      collaborations: 'Collaborations',
      presse: 'Presse',
      contact: 'Contact & booking',
    },
    role: 'Danseur · Chorégraphe · Pédagogue',
    signature: ['Le corps comme géométrie.', 'Les racines comme langage.'],
    preview: 'Préproduction — textes, dates et médias en cours de validation. Les éléments marqués « Exemple » sont fictifs.',
    todo: 'À confirmer',
    example: 'Exemple',
    mediaSoon: 'Image à venir — tournage dédié',
    videoSoon: 'Vidéo à venir — tournage dédié',
    play: 'Lire la vidéo',
    tours: 'Tournées',
    credit: 'Photo',
    photosHd: 'Photos HD sur demande, avec l’accord des photographes.',
    marquee: ['Danse contemporaine', 'Lomé', 'Technique Acogny', 'Danses vodou du Sud', 'Danses du Nord Togo', 'Aské, la lumière', 'Transmission'],
    nextDates: 'Prochaines dates',
    allDates: 'Tout l’agenda',
    noDates: 'Les prochaines dates seront annoncées ici.',
    addCal: 'Ajouter au calendrier',
    places: (n) => (n === 0 ? 'Complet' : n === 1 ? '1 place restante' : `${n} places restantes`),
    newsletter: 'Newsletter',
    newsletterText: 'Créations, tournées, stages. Une lettre par saison.',
    email: 'Adresse e-mail',
    audience: 'Je suis',
    audiencePro: 'Professionnel·le (programmation, presse, institution)',
    audienceStudent: 'Danseur·se, élève',
    subscribe: 'S’inscrire',
    subscribed: 'Merci. Confirmez votre inscription depuis l’e-mail que vous allez recevoir.',
    booking: 'Booking',
    follow: 'Suivre',
    whatsapp: 'Écrire sur WhatsApp',
    rights: 'Tous droits réservés.',
    seeAll: 'Voir toutes les créations',
    program: 'Programmer cette pièce',
    back: 'Retour aux créations',
    filterAll: 'Tout',
    filterFormat: 'Format',
    filterYear: 'Année',
    formats: { solo: 'Solo', duo: 'Duo', groupe: 'Groupe', theatre: 'Théâtre' },
    synopsis: 'Synopsis',
    cast: 'Distribution',
    duration: 'Durée',
    year: 'Création',
    format: 'Format',
    teaser: 'Teaser 30 s',
    gallery: 'Galerie',
    techSheet: 'Fiche technique (PDF)',
    techSheetSoon: 'Fiche technique en préparation',
    tourDates: 'Dates de tournée',
    copy: 'Copier',
    copied: 'Copié',
    send: 'Envoyer',
    required: 'obligatoire',
    formSent: 'Votre messagerie va s’ouvrir avec la demande pré-remplie. Si rien ne se passe, écrivez à',
    country: 'Pays',
    allCountries: 'Tous les pays',
  },
  en: {
    lang: 'English',
    otherLang: 'Français',
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    theme: 'Toggle theme',
    home: 'Home',
    pages: {
      home: 'Home',
      bio: 'Biography',
      creations: 'Works',
      langage: 'The language',
      aske: 'Aské Danse',
      transmission: 'Teaching',
      collaborations: 'Collaborations',
      presse: 'Press',
      contact: 'Contact & booking',
    },
    role: 'Dancer · Choreographer · Teacher',
    signature: ['The body as geometry.', 'Roots as language.'],
    preview: 'Pre-production — texts, dates and media are being validated. Items marked “Example” are fictitious.',
    todo: 'To be confirmed',
    example: 'Example',
    mediaSoon: 'Image coming — dedicated shoot',
    videoSoon: 'Video coming — dedicated shoot',
    play: 'Play video',
    tours: 'Tours',
    credit: 'Photo',
    photosHd: 'HD photos on request, with the photographers’ consent.',
    marquee: ['Contemporary dance', 'Lomé', 'Acogny technique', 'Southern vodou dances', 'Northern Togo dances', 'Aské, the light', 'Teaching'],
    nextDates: 'Upcoming dates',
    allDates: 'Full calendar',
    noDates: 'Upcoming dates will be announced here.',
    addCal: 'Add to calendar',
    places: (n) => (n === 0 ? 'Sold out' : n === 1 ? '1 place left' : `${n} places left`),
    newsletter: 'Newsletter',
    newsletterText: 'Works, tours, workshops. One letter per season.',
    email: 'Email address',
    audience: 'I am',
    audiencePro: 'A professional (programming, press, institution)',
    audienceStudent: 'A dancer or student',
    subscribe: 'Subscribe',
    subscribed: 'Thank you. Please confirm your subscription from the email you are about to receive.',
    booking: 'Booking',
    follow: 'Follow',
    whatsapp: 'Message on WhatsApp',
    rights: 'All rights reserved.',
    seeAll: 'See all works',
    program: 'Book this piece',
    back: 'Back to works',
    filterAll: 'All',
    filterFormat: 'Format',
    filterYear: 'Year',
    formats: { solo: 'Solo', duo: 'Duet', groupe: 'Ensemble', theatre: 'Theatre' },
    synopsis: 'Synopsis',
    cast: 'Cast',
    duration: 'Duration',
    year: 'Premiere',
    format: 'Format',
    teaser: '30 s teaser',
    gallery: 'Gallery',
    techSheet: 'Technical rider (PDF)',
    techSheetSoon: 'Technical rider in preparation',
    tourDates: 'Tour dates',
    copy: 'Copy',
    copied: 'Copied',
    send: 'Send',
    required: 'required',
    formSent: 'Your email app will open with the request pre-filled. If nothing happens, write to',
    country: 'Country',
    allCountries: 'All countries',
  },
};

// Photos trouvées en ligne (presse, 2016–2023). Crédits affichés sous chaque image.
// ⚠ Autorisations de diffusion à obtenir auprès des auteurs avant la mise en ligne publique.
// Fichiers : assets/img/<clé>-<largeur>.webp
export const images = {
  portrait: {
    sizes: [[480, 765], [502, 800]],
    alt: { fr: 'Raouf Tchakondo en studio, en tenue en pagne', en: 'Raouf Tchakondo in the studio, wearing printed wax fabric' },
    credit: 'Togocultures',
    url: 'http://togocultures.com/togo-raouf-tchakondo-lhomme-qui-adore-les-danses-geometriques/',
  },
  'plage-lome': {
    sizes: [[480, 335], [800, 558]],
    alt: { fr: 'Raouf Tchakondo et ses élèves dansent sur la plage de Lomé, sous les cocotiers', en: 'Raouf Tchakondo and his students dancing on the beach in Lomé, under the palm trees' },
    credit: 'Togocultures',
    url: 'http://togocultures.com/togo-raouf-tchakondo-lhomme-qui-adore-les-danses-geometriques/',
  },
  cours: {
    sizes: [[480, 320], [800, 533]],
    alt: { fr: 'Raouf Tchakondo guide un cours, bras ouverts, face à un groupe de danseuses et danseurs', en: 'Raouf Tchakondo leading a class, arms open, facing a group of dancers' },
    credit: 'Siaka S. Traoré',
    url: 'http://togocultures.com/togo-raouf-tchakondo-lhomme-qui-adore-les-danses-geometriques/',
  },
  'stage-djola': {
    sizes: [[480, 270], [960, 540]],
    alt: { fr: 'Stage « Du geste à la danse », 2015 : de jeunes danseurs en mouvement sous un grand préau', en: '“From gesture to dance” workshop, 2015: young dancers moving in a large open-air studio' },
    credit: 'Raouf Tchakondo / YouTube',
    url: 'https://www.youtube.com/watch?v=YMk7W4FL3ts',
  },
  'isis-antigone': {
    sizes: [[480, 320], [960, 640]],
    alt: { fr: 'Isis-Antigone sur scène : une comédienne au centre, danseuse et musiciens autour d’elle', en: 'Isis-Antigone on stage: an actress in the centre, a dancer and musicians around her' },
    credit: 'Christophe Péan',
    url: 'https://sceneweb.fr/isis-antigone-ou-la-tragedie-des-corps-disperses-de-kossi-efoui/',
  },
  releve: {
    sizes: [[480, 492], [780, 800]],
    alt: { fr: 'Une danseuse de la Maison des Artistes Danseurs, bras levés, foulard en kente', en: 'A dancer from the Maison des Artistes Danseurs, arms raised, wearing a kente headscarf' },
    credit: 'L-FRII',
    url: 'https://l-frii.com/togo-zoom-sur-ces-4-danseurs-de-la-maison-des-artistes-danseurs/',
  },
};

// Vidéos YouTube (chargées seulement au clic, via youtube-nocookie)
export const videos = {
  djola: {
    id: 'YMk7W4FL3ts',
    poster: 'stage-djola',
    title: { fr: 'Technique Acogny — extrait « Djola », stage 2015', en: 'Acogny technique — “Djola” excerpt, 2015 workshop' },
  },
};

// Preuves factuelles (cahier des charges, section 2, et sources presse)
export const proofs = {
  fr: [
    { k: '2011', v: 'Assistant de Germaine Acogny, à l’École des Sables' },
    { k: '2005', v: 'Fonde Aské Danse à Lomé. « Aské » : la lumière, en kotokoli' },
    { k: '18', v: 'danseurs, valides et à mobilité réduite, dans Dansons tous ! (2010)' },
    { k: '200', v: 'participants pour le spectacle du Cinquantenaire de l’Indépendance du Togo' },
  ],
  en: [
    { k: '2011', v: 'Assistant to Germaine Acogny at École des Sables' },
    { k: '2005', v: 'Founds Aské Danse in Lomé. “Aské” means light in Kotokoli' },
    { k: '18', v: 'dancers, able-bodied and with reduced mobility, in Dansons tous ! (2010)' },
    { k: '200', v: 'participants in the show for Togo’s 50th anniversary of Independence' },
  ],
};

export const bio = {
  fr: {
    short:
      'Raouf Tchakondo est danseur, chorégraphe et pédagogue, né à Lomé. Il découvre la danse en 1998 avec la Sojaf, rejoint la compagnie Henry Motra, puis danse en Europe pour Harold George. Formé en Belgique, au Centre national de la danse à Pantin et à l’École des Sables, il est l’assistant de Germaine Acogny depuis 2011. En 2005, il fonde Aské Danse. Son écriture relie la géométrie du corps aux danses vodou du Sud et aux danses du Nord Togo.',
    long: [
      'Raouf Tchakondo naît à Lomé et grandit dans le quartier Saint-Joseph, entre vodou, christianisme et islam. À 18 ans, en 1998, il découvre la danse moderne avec la compagnie Sojaf et se forme à l’École de danse traditionnelle, moderne et classique de Lomé.',
      'En 2001, il rejoint la compagnie Henry Motra et se tourne vers la danse contemporaine. À partir de 2003, il travaille avec le chorégraphe sierra-léonais Harold George. Ses pièces le conduisent en Belgique et en tournée dans plusieurs pays d’Europe.',
      'En 2005, il fonde à Lomé la compagnie Aské Danse. « Aské » signifie « lumière » en kotokoli. De 2005 à 2007, il enseigne au Collège régional d’artistes de Dapaong, dans le Nord du pays.',
      'Il se forme ensuite à l’École des Sables, au Sénégal, et au Centre national de la danse, à Pantin (2009). Depuis 2011, il assiste Germaine Acogny dans la transmission de sa technique.',
      'Son écriture part des figures géométriques : « L’élément de base, c’est l’orientation que tu donnes au corps dans l’espace en se calquant sur les figures géométriques : cercles, triangles, losanges, carrés. » Il la nourrit des danses vodou du Sud et des danses traditionnelles du Nord Togo.',
      'Ses pièces parlent du monde : l’esclavage moderne, l’amour, l’eldorado et l’immigration, l’égalité malgré le handicap, la nécessité de s’unir. Kébia et Kola (2008), Nalè et Essime (2009), Dansons tous ! (2010, 18 danseurs valides et à mobilité réduite), L’Œil (2013, joué au Bénin et en Côte d’Ivoire). En 2010, il signe le spectacle du Cinquantenaire de l’Indépendance du Togo, avec 200 participants. Pour le théâtre, il collabore à la chorégraphie d’Isis-Antigone, de Kossi Efoui.',
    ],
  },
  en: {
    short:
      'Raouf Tchakondo is a dancer, choreographer and teacher born in Lomé, Togo. He discovered dance in 1998 with Sojaf, joined the Henry Motra company, then danced in Europe for Harold George. Trained in Belgium, at the Centre national de la danse in Pantin and at École des Sables, he has been assistant to Germaine Acogny since 2011. In 2005 he founded Aské Danse. His work connects the geometry of the body with the vodou dances of southern Togo and the dances of the north.',
    long: [
      'Raouf Tchakondo was born in Lomé and grew up in the Saint-Joseph neighbourhood, between vodou, Christianity and Islam. In 1998, aged 18, he discovered modern dance with the Sojaf company and trained at the School of Traditional, Modern and Classical Dance in Lomé.',
      'In 2001 he joined the Henry Motra company and turned to contemporary dance. From 2003 he worked with Sierra Leonean choreographer Harold George. Those pieces took him to Belgium and on tour across Europe.',
      'In 2005 he founded the Aské Danse company in Lomé. “Aské” means “light” in Kotokoli. From 2005 to 2007 he taught at the Regional College of Artists in Dapaong, in the north of the country.',
      'He went on to train at École des Sables in Senegal and at the Centre national de la danse in Pantin (2009). Since 2011 he has assisted Germaine Acogny in teaching her technique.',
      'His writing starts from geometric figures: “The basic element is the orientation you give the body in space, modelled on geometric figures: circles, triangles, diamonds, squares.” He feeds it with the vodou dances of the South and the traditional dances of northern Togo.',
      'His pieces speak about the world: modern slavery, love, the promised land and immigration, equality despite disability, the need to unite. Kébia et Kola (2008), Nalè et Essime (2009), Dansons tous ! (2010, 18 able-bodied dancers and dancers with reduced mobility), L’Œil (2013, performed in Benin and Côte d’Ivoire). In 2010 he created the show for Togo’s 50th anniversary of Independence, with 200 participants. For the theatre, he collaborated on the choreography of Isis-Antigone by Kossi Efoui.',
    ],
  },
};

// Frise 1998 → 2026 (sources : Africultures, Togocultures)
export const timeline = [
  { year: '1998', place: 'Lomé', color: 'sun', fr: 'Découvre la danse moderne avec la Sojaf. École de danse traditionnelle, moderne et classique.', en: 'Discovers modern dance with Sojaf. School of Traditional, Modern and Classical Dance.' },
  { year: '2001', place: 'Lomé', color: 'ochre', fr: 'Rejoint la compagnie Henry Motra. Cap sur la danse contemporaine.', en: 'Joins the Henry Motra company. Turns to contemporary dance.' },
  { year: '2003', place: 'Belgique', placeEn: 'Belgium', color: 'indigo', fr: 'Danse pour Harold George. Tournées en Europe.', en: 'Dances for Harold George. Tours in Europe.' },
  { year: '2005', place: 'Lomé · Dapaong', color: 'terracotta', fr: 'Fonde Aské Danse, « la lumière ». Enseigne à Dapaong jusqu’en 2007.', en: 'Founds Aské Danse, “the light”. Teaches in Dapaong until 2007.' },
  { year: '2008', place: 'Lomé', color: 'sun', fr: 'Crée Kébia et Kola. Premières formations à l’École des Sables.', en: 'Creates Kébia et Kola. First training at École des Sables.' },
  { year: '2009', place: 'Pantin', color: 'indigo', fr: 'Centre national de la danse. Crée Nalè et Essime.', en: 'Centre national de la danse. Creates Nalè et Essime.' },
  { year: '2010', place: 'Lomé', color: 'terracotta', fr: 'Dansons tous !, 18 danseurs. Spectacle du Cinquantenaire, 200 participants.', en: 'Dansons tous !, 18 dancers. 50th Independence anniversary show, 200 participants.' },
  { year: '2011', place: 'Toubab Dialaw', color: 'ochre', fr: 'Devient l’assistant de Germaine Acogny.', en: 'Becomes assistant to Germaine Acogny.' },
  { year: '2013', place: 'Bénin · Côte d’Ivoire', placeEn: 'Benin · Côte d’Ivoire', color: 'sun', fr: 'L’Œil en tournée.', en: 'L’Œil on tour.' },
  { year: '2026', place: 'Lomé', color: 'terracotta', fr: 'Aské Danse crée, tourne et forme la relève.', en: 'Aské Danse creates, tours and trains the next generation.' },
];

export const lineage = ['Sojaf', 'Henry Motra', 'Harold George', 'Germaine Acogny'];

// Carte : lieux de formation, d'enseignement et de tournée. `year: null` = date à confirmer.
export const places = [
  { name: 'Lomé', lon: 1.23, lat: 6.13, year: 1998, kind: 'base', label: 'below' },
  { name: 'Belgique', nameEn: 'Belgium', lon: 4.35, lat: 50.85, year: 2003, kind: 'formation' },
  { name: 'Dapaong', lon: 0.21, lat: 10.86, year: 2005, kind: 'formation', label: 'left' },
  { name: 'Toubab Dialaw', lon: -17.14, lat: 14.6, year: 2008, kind: 'formation' },
  { name: 'Pantin', lon: 2.41, lat: 48.89, year: 2009, kind: 'formation' },
  { name: 'Bénin', nameEn: 'Benin', lon: 2.42, lat: 6.37, year: 2013, kind: 'tournee', label: 'above' },
  { name: 'Côte d’Ivoire', lon: -4.01, lat: 5.36, year: 2013, kind: 'tournee', label: 'left' },
];

// Répertoire. Les champs null sont à compléter avec la compagnie.
// `shape` : forme géométrique propre à chaque pièce ; `color` : couleur de la vignette.
export const creations = [
  {
    slug: 'kebia-et-kola',
    title: 'Kébia et Kola',
    shape: 'circle',
    color: 'ochre',
    format: null,
    year: '2008',
    duration: null,
    cast: null,
    featured: true,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'nale-et-essime',
    title: 'Nalè et Essime',
    shape: 'losange',
    color: 'indigo',
    format: null,
    year: '2009',
    duration: null,
    cast: null,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'dansons-tous',
    title: 'Dansons tous !',
    shape: 'hexagon',
    color: 'terracotta',
    format: 'groupe',
    year: '2010',
    duration: null,
    cast: { fr: '18 danseurs, valides et à mobilité réduite', en: '18 dancers, able-bodied and with reduced mobility' },
    featured: true,
    synopsis: {
      fr: 'Dix-huit danseurs, valides et à mobilité réduite, sur un même plateau. Une pièce sur l’égalité malgré le handicap. Créée à Lomé en 2010.',
      en: 'Eighteen dancers, able-bodied and with reduced mobility, on one stage. A piece about equality despite disability. Premiered in Lomé in 2010.',
    },
  },
  {
    slug: 'l-oeil',
    title: 'L’Œil',
    shape: 'eye',
    color: 'sun',
    format: null,
    year: '2013',
    duration: null,
    cast: null,
    tours: { fr: 'Bénin, Côte d’Ivoire', en: 'Benin, Côte d’Ivoire' },
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'elle-et-lui',
    title: 'Elle et Lui',
    shape: 'triangle',
    color: 'indigo',
    format: null,
    year: null,
    duration: null,
    cast: null,
    synopsis: { fr: null, en: null },
  },
  {
    slug: 'isis-antigone',
    title: 'Isis-Antigone',
    shape: 'square',
    color: 'terracotta',
    image: 'isis-antigone',
    format: 'theatre',
    year: '2023',
    duration: null,
    featured: true,
    cast: {
      fr: 'Texte : Kossi Efoui. Mise en scène : Gaëtan Noussouglo et Marcel Djondo. Collaboration chorégraphique : Raouf Tchakondo. Avec Florisse Adjanohoun, Roger Kodjo Atikpo, Anani Gbeteglo, Bowokabati Eustache Kamouna, Odile Sankara, Béno Kokou Sanvee.',
      en: 'Text: Kossi Efoui. Directed by Gaëtan Noussouglo and Marcel Djondo. Choreographic collaboration: Raouf Tchakondo. With Florisse Adjanohoun, Roger Kodjo Atikpo, Anani Gbeteglo, Bowokabati Eustache Kamouna, Odile Sankara, Béno Kokou Sanvee.',
    },
    synopsis: {
      fr: 'Comme Antigone, Isis cherche les morceaux dispersés du corps de son frère et époux Osiris. Le spectacle part des corps dispersés et du deuil impossible, une notion présente dans les rituels togolais.',
      en: 'Like Antigone, Isis searches for the scattered pieces of her brother and husband Osiris. The show starts from scattered bodies and impossible mourning, a notion found in Togolese rituals.',
    },
  },
];

// Le langage : danses sources et figures associées (association à valider avec Raouf)
export const sources = [
  {
    id: 'adjogbo',
    name: 'Adjogbo',
    shape: 'circle',
    fr: { origin: 'Sud — vodou', text: 'Dans l’écriture : le cercle. La communauté, la pulsation, le retour.' },
    en: { origin: 'South — vodou', text: 'In the writing: the circle. Community, pulse, return.' },
  },
  {
    id: 'hebiesso',
    name: 'Hébiésso',
    shape: 'triangle',
    fr: { origin: 'Sud — vodou', text: 'Dans l’écriture : le triangle. L’élan, la verticale, la frappe.' },
    en: { origin: 'South — vodou', text: 'In the writing: the triangle. Surge, verticality, strike.' },
  },
  {
    id: 'gadao',
    name: 'Gadao',
    shape: 'losange',
    fr: { origin: 'Nord Togo', text: 'Dans l’écriture : le losange. L’équilibre entre deux appuis.' },
    en: { origin: 'Northern Togo', text: 'In the writing: the diamond. Balance between two points of support.' },
  },
  {
    id: 'kondona',
    name: 'Kondona',
    shape: 'square',
    fr: { origin: 'Nord Togo', text: 'Dans l’écriture : le carré. Le sol, l’ancrage, la stabilité.' },
    en: { origin: 'Northern Togo', text: 'In the writing: the square. Ground, anchoring, stability.' },
  },
  {
    id: 'acogny',
    name: 'Technique Acogny',
    nameEn: 'Acogny technique',
    shape: 'spiral',
    fr: { origin: 'École des Sables', text: 'La colonne vertébrale, les ondulations, la relation au sol. Une technique qu’il transmet aux côtés de Germaine Acogny depuis 2011.' },
    en: { origin: 'École des Sables', text: 'The spine, undulations, the relationship to the ground. A technique he has taught alongside Germaine Acogny since 2011.' },
  },
];

// Agenda. `demo: true` = donnée d'exemple, non publiée en données structurées.
export const agenda = [
  {
    id: 'ex-stage-lome',
    demo: true,
    date: '2026-11-14',
    end: '2026-11-18',
    type: 'stage',
    city: 'Lomé',
    country: 'Togo',
    fr: 'Stage — technique Acogny et écriture géométrique',
    en: 'Workshop — Acogny technique and geometric writing',
    venue: 'Studio Aské Danse',
    price: 45000,
    currency: 'XOF',
    seats: 20,
    left: 7,
  },
  {
    id: 'ex-masterclass-cotonou',
    demo: true,
    date: '2026-12-05',
    end: '2026-12-06',
    type: 'stage',
    city: 'Cotonou',
    country: 'Bénin',
    countryEn: 'Benin',
    fr: 'Masterclass — danses sources du Togo',
    en: 'Masterclass — source dances of Togo',
    venue: null,
    price: 30000,
    currency: 'XOF',
    seats: 16,
    left: 12,
  },
  {
    id: 'ex-spectacle-abidjan',
    demo: true,
    date: '2027-01-23',
    type: 'spectacle',
    city: 'Abidjan',
    country: 'Côte d’Ivoire',
    countryEn: 'Côte d’Ivoire',
    fr: 'Dansons tous ! — représentation',
    en: 'Dansons tous ! — performance',
    piece: 'dansons-tous',
    venue: null,
  },
];

export const quote = {
  fr: 'L’élément de base, c’est l’orientation que tu donnes au corps dans l’espace en se calquant sur les figures géométriques : cercles, triangles, losanges, carrés.',
  en: 'The basic element is the orientation you give the body in space, modelled on geometric figures: circles, triangles, diamonds, squares.',
};

export const pages = {
  fr: {
    home: {
      title: 'Raouf Tchakondo — danseur et chorégraphe, Lomé',
      description:
        'Raouf Tchakondo, danseur, chorégraphe et pédagogue togolais. Assistant de Germaine Acogny, fondateur d’Aské Danse. Créations, stages, booking.',
      manifesto: 'Vidéo manifeste — 60 s',
      ctaWorks: 'Voir les créations',
      ctaBook: 'Programmer une pièce',
      featured: 'Créations',
      proofTitle: 'Repères',
      mapTitle: 'Formations et tournées',
      mapText: 'De Lomé à Bruxelles, de Pantin à Toubab Dialaw. Les villes s’allument année après année.',
      mapLink: 'Voir le parcours complet',
      pathsTitle: 'Vous êtes',
      paths: [
        { who: 'Programmateur·rice', what: 'Répertoire, fiches techniques, devis de tournée', to: 'creations' },
        { who: 'Institution, bailleur', what: 'Parcours, engagement social, résidences', to: 'bio' },
        { who: 'Danseur·se, élève', what: 'Stages, masterclasses, inscription en ligne', to: 'transmission' },
        { who: 'Marque, agence', what: 'Chorégraphie de lancement, clip, cérémonie', to: 'collaborations' },
        { who: 'Journaliste, chercheur·se', what: 'Bios, photos HD, articles', to: 'presse' },
      ],
      placesTitle: 'Lieux de formation',
      placesNote: 'Logos partenaires : autorisations en cours.',
      lightKicker: 'Aské Danse',
      lightTitle: 'Aské, en kotokoli, c’est la lumière.',
      lightText: 'Depuis 2005, la compagnie crée, tourne et forme à Lomé une nouvelle génération de danseurs.',
      lightCta: 'Découvrir la compagnie',
      galleryTitle: 'En mouvement',
      galleryText: 'Sur la plage de Lomé, en studio, sur scène. Là où il danse, il transmet.',
      videoTitle: 'Le voir transmettre',
      videoText: 'Stage « Du geste à la danse. Le danseur interprète », 2015. Extrait « Djola ».',
      quoteSrc: 'Raouf Tchakondo, Togocultures, 2016',
    },
    bio: {
      title: 'Biographie',
      description: 'Biographie de Raouf Tchakondo : de la Sojaf à Germaine Acogny, la fondation d’Aské Danse, 1998 → 2026.',
      lead: 'Né à Lomé. Formé à Lomé, Bruxelles, Pantin et Toubab Dialaw. Assistant de Germaine Acogny depuis 2011.',
      shortTitle: 'En 80 mots',
      longTitle: 'Parcours',
      timelineTitle: '1998 → 2026',
      lineageTitle: 'Filiation',
      lineageText: 'Une transmission de maître à élève, jusqu’à la référence de la danse africaine contemporaine.',
    },
    creations: {
      title: 'Créations',
      description: 'Le répertoire de Raouf Tchakondo et d’Aské Danse : Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui, Isis-Antigone.',
      lead: 'Depuis 2008, une écriture qui parle du monde. Chaque pièce a sa forme.',
    },
    langage: {
      title: 'Le langage',
      description: 'L’écriture chorégraphique de Raouf Tchakondo : géométrie du corps, danses vodou du Sud et danses du Nord Togo, technique Acogny.',
      lead: 'Une écriture fondée sur les figures géométriques, nourrie des danses vodou du Sud et des danses traditionnelles du Nord Togo.',
      intro: [
        'Le corps trace des figures. Un cercle au sol, un triangle dans l’espace, un losange entre deux appuis.',
        'Ces figures ne sont pas des décors. Elles organisent le mouvement, les trajectoires, les relations entre danseurs.',
        'Chaque figure a une source : une danse apprise, transmise, retravaillée.',
      ],
      moduleTitle: 'Les sources',
      moduleHint: 'Choisissez une danse pour voir sa figure.',
      interview: 'Entretien — le langage chorégraphique (sous-titré FR / EN)',
      videoTitle: 'La technique Acogny, transmise par Raouf',
    },
    aske: {
      title: 'Aské Danse',
      description: 'Aské Danse, compagnie de danse contemporaine fondée à Lomé en 2005 par Raouf Tchakondo. Répertoire, danseurs, recrutement.',
      lead: 'Compagnie fondée à Lomé en 2005. Elle crée, tourne et forme.',
      history: [
        'Aské Danse naît à Lomé en 2005. « Aské » signifie « lumière » en kotokoli. Raouf Tchakondo la fonde pour porter ses créations et pour former des danseurs.',
        'La compagnie accompagne une nouvelle génération : les danseurs de la Maison des Artistes Danseurs, le collectif Street Kings.',
        'Ses interprètes sont un vivier professionnel pour les festivals, les théâtres et les productions de la région.',
      ],
      dancersTitle: 'Les danseurs',
      dancersNote: 'Portraits vidéo en boucle — tournage à venir.',
      relTitle: 'La relève',
      rel: [
        { name: 'Maison des Artistes Danseurs', text: 'Formation de jeunes interprètes.' },
        { name: 'Street Kings', text: 'Des danses urbaines à la scène contemporaine.' },
      ],
      repTitle: 'Répertoire',
      recruitTitle: 'Recrutement',
      recruitText: 'Vous êtes danseur ou danseuse et souhaitez rejoindre la compagnie ? Envoyez une présentation et un lien vidéo.',
      recruitCta: 'Candidater',
    },
    transmission: {
      title: 'Transmission',
      description: 'Stages et masterclasses de danse contemporaine avec Raouf Tchakondo : technique Acogny, danses sources du Togo. Inscription et paiement en ligne.',
      lead: 'Stages, masterclasses, cours. La technique Acogny et les danses sources du Togo.',
      offers: [
        { t: 'Stages', d: 'Plusieurs jours de travail intensif. Technique, répertoire, écriture.' },
        { t: 'Masterclasses', d: 'Une ou deux journées, en festival ou en institution.' },
        { t: 'Cours en ligne', d: 'Il a déjà enseigné en direct pour les « Mercredis de danse » de l’École des Sables. Cours vidéo à venir.' },
      ],
      agendaTitle: 'Agenda des stages',
      formTitle: 'Inscription',
      session: 'Session',
      qty: 'Nombre de places',
      name: 'Nom complet',
      phone: 'Téléphone',
      level: 'Niveau',
      levels: ['Débutant', 'Intermédiaire', 'Professionnel'],
      pay: 'Paiement',
      payMomo: 'Mobile money',
      payCard: 'Carte bancaire',
      total: 'Total',
      submit: 'Réserver et payer',
      demoPay: 'Paiement en préproduction : la réservation est transmise par e-mail, le paiement FedaPay / Stripe sera activé au lancement.',
      schoolTitle: 'Écoles et institutions',
      schoolText: 'Ateliers sur mesure pour écoles, conservatoires et centres culturels.',
    },
    collaborations: {
      title: 'Collaborations',
      description: 'Chorégraphie pour le théâtre, les clips, les marques et les événements. Envoyez votre brief à Raouf Tchakondo.',
      lead: 'Théâtre, clips, marques, événements. Une écriture reconnaissable, au service d’un projet.',
      fields: [
        { t: 'Théâtre', d: 'Isis-Antigone, de Kossi Efoui : collaboration chorégraphique.' },
        { t: 'Clips', d: 'Chorégraphie et direction de danseurs pour la musique.' },
        { t: 'Marques', d: 'Lancements, films, activations.' },
        { t: 'Événements', d: 'Cérémonies, ouvertures, grands formats : le Cinquantenaire, 200 participants.' },
      ],
      casesTitle: 'Références',
      casesNote: '',
      cases: [
        { t: 'Isis-Antigone', k: 'Théâtre · 2023', d: 'Collaboration chorégraphique pour la pièce de Kossi Efoui, mise en scène par Gaëtan Noussouglo et Marcel Djondo.', image: 'isis-antigone', to: 'isis-antigone' },
        { t: 'Cinquantenaire de l’Indépendance', k: 'Événement · Lomé · 2010', d: 'Le spectacle des 50 ans de l’Indépendance du Togo. 200 participants.', color: 'sun' },
      ],
      briefTitle: 'Votre brief',
    },
    presse: {
      title: 'Presse',
      description: 'Espace presse de Raouf Tchakondo : biographies courte et longue, photos HD, kit presse, contact.',
      lead: 'Biographies, photos, kit presse. Tout en un clic.',
      kitTitle: 'Kit presse',
      kitItems: ['Biographies courte et longue', 'Photos HD (fond noir, fond blanc)', 'Logos', 'Fiches des créations'],
      kitCta: 'Télécharger le kit presse',
      kitSoon: 'Le kit complet (PDF + ZIP) sera généré depuis le CMS. En attendant, demandez-le par e-mail.',
      bioShort: 'Bio courte',
      bioLong: 'Bio longue',
      articlesTitle: 'Ils en parlent',
      articles: [
        { src: 'Togocultures', t: 'Raouf Tchakondo, l’homme qui adore les danses géométriques — Gaëtan Noussouglo', y: '2016', url: 'http://togocultures.com/togo-raouf-tchakondo-lhomme-qui-adore-les-danses-geometriques/' },
        { src: 'Africultures', t: 'Fiche Raouf Tchakondo', y: null, url: 'http://africultures.com/personnes/?no=8584' },
        { src: 'Sceneweb', t: 'Isis-Antigone ou la tragédie des corps dispersés, de Kossi Efoui', y: '2023', url: 'https://sceneweb.fr/isis-antigone-ou-la-tragedie-des-corps-disperses-de-kossi-efoui/' },
        { src: 'L-FRII', t: 'Zoom sur 4 danseurs de la Maison des Artistes Danseurs', y: '2022', url: 'https://l-frii.com/togo-zoom-sur-ces-4-danseurs-de-la-maison-des-artistes-danseurs/' },
        { src: 'YouTube', t: 'Technique Acogny by Raouf Tchakondo', y: '2015', url: 'https://www.youtube.com/watch?v=YMk7W4FL3ts' },
      ],
      creditsTitle: 'Crédits photo',
      contactTitle: 'Contact presse',
    },
    contact: {
      title: 'Contact & booking',
      description: 'Booking Raouf Tchakondo et Aské Danse : tournée, atelier, collaboration, presse.',
      lead: 'Tournée, atelier, collaboration, presse. Chaque demande reçoit une réponse.',
      type: 'Type de demande',
      types: { tournee: 'Tournée / programmation', atelier: 'Atelier / masterclass', collaboration: 'Collaboration', presse: 'Presse', autre: 'Autre' },
      piece: 'Pièce concernée',
      pieceNone: 'Aucune en particulier',
      org: 'Structure',
      name: 'Nom',
      email: 'E-mail',
      phone: 'Téléphone / WhatsApp',
      dates: 'Dates envisagées',
      place: 'Ville, pays',
      budget: 'Budget indicatif',
      budgets: ['Non défini', '< 1 000 €', '1 000 – 5 000 €', '5 000 – 15 000 €', '> 15 000 €'],
      message: 'Message',
    },
  },
  en: {
    home: {
      title: 'Raouf Tchakondo — dancer and choreographer, Lomé',
      description:
        'Raouf Tchakondo, Togolese dancer, choreographer and teacher. Assistant to Germaine Acogny, founder of Aské Danse. Works, workshops, booking.',
      manifesto: 'Manifesto video — 60 s',
      ctaWorks: 'See the works',
      ctaBook: 'Book a piece',
      featured: 'Works',
      proofTitle: 'Landmarks',
      mapTitle: 'Training and touring',
      mapText: 'From Lomé to Brussels, from Pantin to Toubab Dialaw. The cities light up year after year.',
      mapLink: 'See the full journey',
      pathsTitle: 'You are',
      paths: [
        { who: 'A programmer', what: 'Repertoire, technical riders, touring quote', to: 'creations' },
        { who: 'An institution or funder', what: 'Career, social impact, residencies', to: 'bio' },
        { who: 'A dancer or student', what: 'Workshops, masterclasses, online booking', to: 'transmission' },
        { who: 'A brand or agency', what: 'Launch choreography, music video, ceremony', to: 'collaborations' },
        { who: 'A journalist or researcher', what: 'Bios, HD photos, articles', to: 'presse' },
      ],
      placesTitle: 'Where he trained',
      placesNote: 'Partner logos: permissions in progress.',
      lightKicker: 'Aské Danse',
      lightTitle: 'In Kotokoli, Aské means light.',
      lightText: 'Since 2005 the company has created, toured and trained a new generation of dancers in Lomé.',
      lightCta: 'Discover the company',
      galleryTitle: 'In motion',
      galleryText: 'On the beach in Lomé, in the studio, on stage. Wherever he dances, he teaches.',
      videoTitle: 'Watch him teach',
      videoText: '“From gesture to dance. The dancer as interpreter” workshop, 2015. “Djola” excerpt.',
      quoteSrc: 'Raouf Tchakondo, Togocultures, 2016',
    },
    bio: {
      title: 'Biography',
      description: 'Biography of Raouf Tchakondo: from Sojaf to Germaine Acogny, founding Aské Danse, 1998 → 2026.',
      lead: 'Born in Lomé. Trained in Lomé, Brussels, Pantin and Toubab Dialaw. Assistant to Germaine Acogny since 2011.',
      shortTitle: 'In 80 words',
      longTitle: 'Journey',
      timelineTitle: '1998 → 2026',
      lineageTitle: 'Lineage',
      lineageText: 'A transmission from teacher to student, up to the reference of contemporary African dance.',
    },
    creations: {
      title: 'Works',
      description: 'The repertoire of Raouf Tchakondo and Aské Danse: Kébia et Kola, Nalè et Essime, Dansons tous !, L’Œil, Elle et Lui, Isis-Antigone.',
      lead: 'Since 2008, a body of work that speaks about the world. Each piece has its own shape.',
    },
    langage: {
      title: 'The language',
      description: 'Raouf Tchakondo’s choreographic language: geometry of the body, southern vodou dances and northern Togolese dances, Acogny technique.',
      lead: 'A choreographic writing built on geometric figures, fed by the vodou dances of the South and the traditional dances of northern Togo.',
      intro: [
        'The body draws figures. A circle on the floor, a triangle in space, a diamond between two points of support.',
        'These figures are not decoration. They organise movement, trajectories, the relationships between dancers.',
        'Each figure has a source: a dance learned, passed on, reworked.',
      ],
      moduleTitle: 'The sources',
      moduleHint: 'Choose a dance to see its figure.',
      interview: 'Interview — the choreographic language (FR / EN subtitles)',
      videoTitle: 'The Acogny technique, taught by Raouf',
    },
    aske: {
      title: 'Aské Danse',
      description: 'Aské Danse, contemporary dance company founded in Lomé in 2005 by Raouf Tchakondo. Repertoire, dancers, auditions.',
      lead: 'A company founded in Lomé in 2005. It creates, tours and trains.',
      history: [
        'Aské Danse was born in Lomé in 2005. “Aské” means “light” in Kotokoli. Raouf Tchakondo founded it to carry his works and to train dancers.',
        'The company supports a new generation: the dancers of the Maison des Artistes Danseurs, the Street Kings collective.',
        'Its performers are a professional talent pool for festivals, theatres and productions across the region.',
      ],
      dancersTitle: 'The dancers',
      dancersNote: 'Looping video portraits — shoot coming.',
      relTitle: 'The next generation',
      rel: [
        { name: 'Maison des Artistes Danseurs', text: 'Training young performers.' },
        { name: 'Street Kings', text: 'From urban dance to the contemporary stage.' },
      ],
      repTitle: 'Repertoire',
      recruitTitle: 'Auditions',
      recruitText: 'Are you a dancer who would like to join the company? Send a short introduction and a video link.',
      recruitCta: 'Apply',
    },
    transmission: {
      title: 'Teaching',
      description: 'Contemporary dance workshops and masterclasses with Raouf Tchakondo: Acogny technique, source dances of Togo. Online booking and payment.',
      lead: 'Workshops, masterclasses, classes. The Acogny technique and the source dances of Togo.',
      offers: [
        { t: 'Workshops', d: 'Several days of intensive work. Technique, repertoire, writing.' },
        { t: 'Masterclasses', d: 'One or two days, at festivals or institutions.' },
        { t: 'Online classes', d: 'He has already taught live for École des Sables’ “Dance Wednesdays”. Video classes coming soon.' },
      ],
      agendaTitle: 'Workshop calendar',
      formTitle: 'Registration',
      session: 'Session',
      qty: 'Number of places',
      name: 'Full name',
      phone: 'Phone',
      level: 'Level',
      levels: ['Beginner', 'Intermediate', 'Professional'],
      pay: 'Payment',
      payMomo: 'Mobile money',
      payCard: 'Card',
      total: 'Total',
      submit: 'Book and pay',
      demoPay: 'Pre-production payment: your booking is sent by email; FedaPay / Stripe payment will be enabled at launch.',
      schoolTitle: 'Schools and institutions',
      schoolText: 'Tailored workshops for schools, conservatoires and cultural centres.',
    },
    collaborations: {
      title: 'Collaborations',
      description: 'Choreography for theatre, music videos, brands and events. Send your brief to Raouf Tchakondo.',
      lead: 'Theatre, music videos, brands, events. A recognisable language, at the service of a project.',
      fields: [
        { t: 'Theatre', d: 'Isis-Antigone by Kossi Efoui: choreographic collaboration.' },
        { t: 'Music videos', d: 'Choreography and dancer direction for music.' },
        { t: 'Brands', d: 'Launches, films, activations.' },
        { t: 'Events', d: 'Ceremonies, openings, large formats: the 50th anniversary show, 200 participants.' },
      ],
      casesTitle: 'References',
      casesNote: '',
      cases: [
        { t: 'Isis-Antigone', k: 'Theatre · 2023', d: 'Choreographic collaboration on Kossi Efoui’s play, directed by Gaëtan Noussouglo and Marcel Djondo.', image: 'isis-antigone', to: 'isis-antigone' },
        { t: '50th anniversary of Independence', k: 'Event · Lomé · 2010', d: 'The show for Togo’s 50th anniversary of Independence. 200 participants.', color: 'sun' },
      ],
      briefTitle: 'Your brief',
    },
    presse: {
      title: 'Press',
      description: 'Raouf Tchakondo press area: short and long bios, HD photos, press kit, contact.',
      lead: 'Bios, photos, press kit. All in one click.',
      kitTitle: 'Press kit',
      kitItems: ['Short and long bios', 'HD photos (black and white backgrounds)', 'Logos', 'Work sheets'],
      kitCta: 'Download the press kit',
      kitSoon: 'The full kit (PDF + ZIP) will be generated from the CMS. Meanwhile, request it by email.',
      bioShort: 'Short bio',
      bioLong: 'Long bio',
      articlesTitle: 'Coverage',
      articles: [
        { src: 'Togocultures', t: 'Raouf Tchakondo, the man who loves geometric dances — Gaëtan Noussouglo (FR)', y: '2016', url: 'http://togocultures.com/togo-raouf-tchakondo-lhomme-qui-adore-les-danses-geometriques/' },
        { src: 'Africultures', t: 'Raouf Tchakondo profile (FR)', y: null, url: 'http://africultures.com/personnes/?no=8584' },
        { src: 'Sceneweb', t: 'Isis-Antigone by Kossi Efoui (FR)', y: '2023', url: 'https://sceneweb.fr/isis-antigone-ou-la-tragedie-des-corps-disperses-de-kossi-efoui/' },
        { src: 'L-FRII', t: 'Four dancers of the Maison des Artistes Danseurs (FR)', y: '2022', url: 'https://l-frii.com/togo-zoom-sur-ces-4-danseurs-de-la-maison-des-artistes-danseurs/' },
        { src: 'YouTube', t: 'Technique Acogny by Raouf Tchakondo', y: '2015', url: 'https://www.youtube.com/watch?v=YMk7W4FL3ts' },
      ],
      creditsTitle: 'Photo credits',
      contactTitle: 'Press contact',
    },
    contact: {
      title: 'Contact & booking',
      description: 'Booking Raouf Tchakondo and Aské Danse: touring, workshops, collaborations, press.',
      lead: 'Touring, workshops, collaborations, press. Every request gets an answer.',
      type: 'Request type',
      types: { tournee: 'Touring / programming', atelier: 'Workshop / masterclass', collaboration: 'Collaboration', presse: 'Press', autre: 'Other' },
      piece: 'Piece',
      pieceNone: 'None in particular',
      org: 'Organisation',
      name: 'Name',
      email: 'Email',
      phone: 'Phone / WhatsApp',
      dates: 'Proposed dates',
      place: 'City, country',
      budget: 'Indicative budget',
      budgets: ['Not defined', '< €1,000', '€1,000 – 5,000', '€5,000 – 15,000', '> €15,000'],
      message: 'Message',
    },
  },
};
